Repository BE-Team2/Team-Work-Practice, pull requests merged in 2023-01, with the labels that each got.

#2 docs: README.md에 자기소개 추가
  README.md
Labels: For: Backend, Priority: Critical, Status: Available, Type: Documentation

#3 피즈버즈 몬티 리드미 했습니
  README.md
  fb.md
  monty.md
Labels: For: Backend, Priority: Critical, Type: Documentation

#6 Develop #4
  README.md
  fb.md
  monty.md
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Documentation

#8 #7 - README.md, fb.md, monty.md Pull Requests
  README.md
  fb.md
  monty.md
Labels: For: Backend, Priority: Medium, Status: Available, Type: Documentation

#9 README.md, fb.md, monty.md 수정완료
  README.md
  fb.md
  monty.md
Labels: For: Backend, Priority: Medium, Status: Available, Type: Documentation
